### ISSUE TITLE
Feature Request: Ability to specify a HTTP source

### ISSUE THREAD

**Issue by webnoob** [quasarframework/app-extension-icon-factory#38]
Rather than being forced to supply a local source file, it would be nice to pass along a URL to a file.

**Comment by nothingismagick** [comment]
I've been thinking about this, and I am worried about injections at runtime. What happens if you specify for example a file that is 4TB in size?

**Comment by nothingismagick** [comment]
For the CLI and the Quasar Ext I think its better not to do this.
