### ISSUE TITLE
icons not copied to: /src-cordova/platforms/ios/ProjectName/Images.xcassets

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/app-extension-icon-factory#45]
It seems the icons in `/src-cordova/platforms/ios/ProjectName/Images.xcassets` where `ProjectName` is the actual name of my app, **are not overwritten** by app-extension-icon-factory.

They stay the default Cordova icons, even after removing and re-adding the platform.

This makes it so in XCode only the Cordova icons are picked up:
<img width="523" alt="image" src="https://user-images.githubusercontent.com/3253920/54861689-d95df480-4d70-11e9-9c3f-bd74618c888a.png">

PS: the icons for iOS cannot have a transparent bg or alpha layer, else I cannot upload my app to Testflight. 😣

**Comment by mesqueeb** [comment]
edited the post to be more to the point and accurate

**Comment by nothingismagick** [comment]
Thanks for the report. I'll dig I to this tomorrow.

**Comment by nothingismagick** [comment]
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/


|Attribute | Value|
|-- | --|
|Format | PNG
|Color space | sRGB or P3 (see Color Management)
|Layers | Flattened with no transparency
|Resolution | Varies. See Image Size and Resolution
|Shape | Square with no rounded corners

**Comment by nothingismagick** [comment]
Well, this means we absolutely CANNOT have transparent backgrounds for iOS.

**Comment by nothingismagick** [comment]
It seems that we need to add some linkage to the config.xml, like this stuff:

```
    <platform name="android">
        <icon density="ldpi" src="res/icon/android/icon-36-ldpi.png" />
        <icon density="mdpi" src="res/icon/android/icon-48-mdpi.png" />
        <icon density="hdpi" src="res/icon/android/icon-72-hdpi.png" />
        <icon density="xhdpi" src="res/icon/android/icon-96-xhdpi.png" />
        <icon density="xxhdpi" src="res/icon/android/icon-144-xxhdpi.png" />
        <icon density="xxxhdpi" src="res/icon/android/icon-192-xxxhdpi.png" />
    </platform>
```

**Comment by mesqueeb** [comment]
Or you could place them inside `/src-cordova/platforms/ios/ProjectName/Images.xcassets` but i guess that's more difficult since on the very first build that folder doesn't exist.

**Comment by nothingismagick** [comment]
We're also considering adding a tag like this:
i.e., <platform name="android" quasar-controlled="true"></platform>
to the config.xml - but am waiting for a design review from the rest of the team to make sure we do this according to best practice AND to current Quasar CODEX

It might take me a few days to resolve this, but thankyou so very much for raising this issue.

**Comment by mesqueeb** [comment]
No problemo!! Take your time. I am using cordova-icon in the meanwhile.

**Comment by nothingismagick** [comment]
We're tracking this and I should have a preview for you tomorrow.

**Comment by nothingismagick** [comment]
see: https://github.com/quasarframework/app-extension-icon-factory/commit/7737dbe1d4380b3d46ab143667042594db0b3d00

**Comment by mesqueeb** [comment]
Great!🏄🏼‍♂️
Let me know on Discord if I need to test anything! 🏓

**Comment by mesqueeb** [comment]
Thank you for your awesome work! 
# 🎉
