### ISSUE TITLE
Update installation to request background color.

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/app-extension-icon-factory#46]
It seems that iOS will not permit transparent app-icon colors. Let's default to white #ffffff - and offer the dev the option to set another one.

We may have to enhance the internal interface to add background color on iOS.

**Comment by donmbelembe** [comment]
the images generated for splash screen have a black background, how to change it

**Comment by nothingismagick** [comment]
This will be fixed ASAP @donmbelembe - I just made changes so that when you install (or reinstall the extension) it asks you for a background color.

**Comment by NicksonYap** [comment]
@nothingismagick The readme in npm repo seems to mention Splashscreen background color

https://www.npmjs.com/package/@quasar/quasar-app-extension-icon-factory 

However I still wasn't prompt for background color, turns out source code is using previous version (1.0.0-beta.9)

**Comment by nothingismagick** [comment]
Thanks - I must have missed publishing it to npm somehow. 
Now it should be available. as 1.0.0-beta.10

**Comment by donmbelembe** [comment]
thanks for fixing, I just wanted to know how to specify the bg color, in the quasar.variables.styl or the config.xml ?

**Comment by nothingismagick** [comment]
this is specified in the quasar.icon-factory.json file - and you do this by reinstalling the extension:
```
$ quasar ext add @quasar/icon-factory
```
And answering the questions about the background color.

**Comment by donmbelembe** [comment]
it still generating with a black bg

**Comment by nothingismagick** [comment]
I see - not sure why that happened, will resolve shortly.

**Comment by nothingismagick** [comment]
This is resolved in beta.11 - thanks for reporting!!!
