### ISSUE TITLE
quasar dev -m cordova hangs with icon-factory installed

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/app-extension-icon-factory#48]
Hi,

MacOS, "quasar dev -m cordova -T ios".
Sorry for not detailing more because of time constraints. Logging here so it doesn't gets lost. I may get to fixing this if time will allow. Feel free to take a crack at it.

-Razvan

**Comment by nothingismagick** [comment]
Cordova is on my radar. I’ll look into it.

>

**Comment by nothingismagick** [comment]
This is no longer an issue. Dev works as does build. The hang is gone.
