### ISSUE TITLE
RFC - Usage

### ISSUE THREAD

**Issue by rstoenescu** [quasarframework/app-extension-icon-factory#49]
Overall, this RFC is for making usage much easier and speeding up dev/build time.

1. Rather than creating images each time dev/build commands run, I propose the AE:
  * registering command to generate them (optionally asking about how to do it and/or through command params)
  * dev/build hooks (from index AE script) checking if icons are already generated and if so then skipping creation; otherwise generate the icons for first time;
    - additional mechanism: storing hash of source png file and comparing last image used to generate icons with current hash of file to determine if dev/build should rebuild icons; one hash per Quasar mode used (so that generating with a mode then with another doesn't wrongly skips updating icons)
  * this would also allow for us to drop prompting user about the dev vs build algorithm to use for icons

2. Cordova
  * automatically injecting needed config in src-cordova/config.xml so that the icons + splashscreen are picked up -- so no user further interaction needed; ref from what I did in quasar/app: [managing the config.xml file](https://github.com/quasarframework/quasar/blob/dev/app/lib/cordova/cordova-config.js) through `elementtree` package
  * splashscreens require a cordova package installed into Cordova project (/src-cordova) --> maybe a warning about this when icon-factory generates icons?

PS: Sorry for the bullet-style approach with this RFC due to time constraints.

**Comment by nothingismagick** [comment]
Actually, we aren't creating the images each time. There is a hashing involved. Your description of point 1 is exactly what SHOULD be happening.

**Comment by nothingismagick** [comment]
compare: https://github.com/quasarframework/app-extension-icon-factory/blob/6528b055f7674c15d3b92c64b5517ce47642108c/src/index.js#L75

**Comment by rstoenescu** [comment]
Good. Then what about dropping the prompt and using only one method regardless if command is dev/build?

**Comment by nothingismagick** [comment]
Well, it could be an option to use the same strategy, but for example the
use case is that you want lossy low-quality during development, but
smallest file during build. That can mean a difference of minutes (if you
are using extreme lossless compression).

>

**Comment by rstoenescu** [comment]
If it's a difference of minutes, then we can scratch off point 1.

**Comment by nothingismagick** [comment]
These points have all been resolved.
