### ISSUE TITLE
 app Unknown command "ext" +2ms

### ISSUE THREAD

**Issue by fega** [quasarframework/app-extension-icon-factory#50]
I'm gettings this when i try to install it

**Comment by nothingismagick** [comment]
You need to be on @quasar/cli 1.0.0-beta.4

**Comment by fega** [comment]
@nothingismagick would be great to add that info to the docs

**Comment by nothingismagick** [comment]
You're right. I'll do that now.

**Comment by andreydos** [comment]
npm install -g @quasar/cli
Result:
+ @quasar/cli@1.0.5
added 294 packages from 226 contributors in 33.428s


quasar ext add @quasar/icon-genie
Result:
Error Unknown command "ext"
