### ISSUE TITLE
RFC - Gradient Backgrounds

### ISSUE THREAD

**Issue by nothingismagick** [quasarframework/app-extension-icon-factory#52]
I've been thinking about ways to enable gradient backgrounds. Is this something people would find useful? I see two ways to do this:
1. You provide a background
2. The gradient is created internally

They both have plus sides and downsides, and I don't know if this is really something people want. I sort of tend to think it is too fancy, and if you want that you should just provide your icon with the gradient embedded in it.

**Comment by tohagan** [comment]
Yes!
