### ISSUE TITLE
[low-priority] Changing the bg colour doesn't trigger re-build

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/app-extension-icon-factory#54]
steps to reproduce:
1. I reinstalled the icon-factory and gone through the setup
2. I chose a bg colour
3. I built for cordova-ios
4. I changed "background_color" in `quasar.icon-factory.json` and `quasar.extensions.json`
5. I built again for cordova-ios
  → the icons are not generated with new background colours.

### workaround

delete all the generated icons once

**Comment by nothingismagick** [comment]
Thanks for reporting this - I have now added a new flag during install that you can set to ALWAYS rebuild the icons, to turn it off you would change or delete that flag.

I have also added an additional check to see if the background value in quasar.extensions.json === the value in quasar.icon-factory.json

Will be available in the next beta
