### ISSUE TITLE
Sharp 21.3 fails to install on MacOS

### ISSUE THREAD

**Issue by informatious** [quasarframework/app-extension-icon-factory#55]
Sharp 21.3 fails to install on MacOS, any chance you could bump it to the latest version (22.1)?

**Comment by nothingismagick** [comment]
Can you please post specific details about your environment?

OS version as well as the complete results from

$ quasar info

I use this on a daily basis with MacOS

>

**Comment by nothingismagick** [comment]
@informatious - updated in beta.25
This should resolve it for you.
```
$ quasar ext remove @quasar/icon-factory
$ quasar ext add @quasar/icon-factory
```

Thanks for letting me know.
