### ISSUE TITLE
Running Build/Dev Can Produce a nested src-cordova folder

### ISSUE THREAD

**Issue by jpgilchrist** [quasarframework/app-extension-icon-factory#58]
If you happen to be in src-cordova already then icon-factory will create a nested src-cordova folder

```
cd src-cordova
quasar build -m cordova -T android --debug
```

![image](https://user-images.githubusercontent.com/5065660/57719566-05e60c80-764e-11e9-8af2-42c6c8d19817.png)

**Comment by nothingismagick** [comment]
Resolved in rc.2
