### ISSUE TITLE
Ability to delete app-splashscreen.png

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/app-extension-icon-factory#60]
I love the RC of icon-factory 🎉

I chose as splashscreen strategy  "use icon with color as bg for splash" so, I deleted that warning icon about the splashscreen, but then I get this error on building:

> Error: File not found: /Users/lucaban/.ghq/github.com/mesqueeb/sokketsu/app-splashscreen.png

I think most devs would intuitively delete the app-splashscreen.png with the big warning, in case they just use an icon with a single bg color for splash screen.

**and / or**

have it not generate `app-splashscreen.png` if "use icon with color as bg for splash" is chosen?

**Comment by nothingismagick** [comment]
Will be fixed in 1.0.0
