### ISSUE TITLE
Missing some iOS icons

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/app-extension-icon-factory#61]
Noticed we are still missing icons for iOS.
On XCode if I inspect the assets, I can find these missing ones (more details below):

<img width="219" alt="image" src="https://user-images.githubusercontent.com/3253920/57768374-783a1800-7746-11e9-8370-6cad6a9731d5.png">

<img width="212" alt="image" src="https://user-images.githubusercontent.com/3253920/57768391-81c38000-7746-11e9-89ae-4bec0bbae629.png">

<img width="219" alt="image" src="https://user-images.githubusercontent.com/3253920/57768374-783a1800-7746-11e9-8370-6cad6a9731d5.png">

<img width="543" alt="image" src="https://user-images.githubusercontent.com/3253920/57768415-8a1bbb00-7746-11e9-8f7d-ffc84e4cf4fe.png">

<hr>

Location:

-`src-cordova/platform/ios/AppName/Images.xcassets/AppIcon.appiconset`

Files I took from this folder:

[missing icons.zip](https://github.com/quasarframework/app-extension-icon-factory/files/3182165/missing.icons.zip)

**Comment by mesqueeb** [comment]
I'm not sure if these are the icons you are looking for...
Should I also search inside my `src-cordova/res/` folder?

**Comment by nothingismagick** [comment]
Thanks! That's perfect.

**Comment by mesqueeb** [comment]
Btw i’m using cordova with ios5
Dont know if the version is important ^^
