### ISSUE TITLE
Extension always rebuild image set

### ISSUE THREAD

**Issue by Makeyko** [quasarframework/app-extension-icon-factory#64]
"build_always" flag set to false
and no changes with source image
Any run of `quasar dev` rebuilds all images

**Comment by nothingismagick** [comment]
Can you share the results of quasar info

**Comment by Makeyko** [comment]
Operating System - Darwin(18.6.0) - darwin/x64
NodeJs - 11.15.0

Global packages
  NPM - 6.9.1-next.0
  yarn - 1.16.0
  @quasar/cli - 1.0.0-beta.7
  cordova - Not installed

Important local packages
  quasar - 1.0.0-rc.4 -- High performance, Material Design 2, full front end stack with Vue.js -- build SPA, SSR, P
WA, Hybrid Mobile Apps and Electron apps, all simultaneously using the same codebase
  @quasar/app - 1.0.0-rc.5 -- Quasar Framework App CLI
  @quasar/extras - 1.1.2 -- Quasar Framework fonts, icons and animations
  vue - 2.6.10 -- Reactive, component-oriented view layer for modern web interfaces.
  vue-router - 3.0.6 -- Official router for Vue.js 2
  vuex - 3.1.1 -- state management for Vue.js
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  @babel/core - 7.4.5 -- Babel compiler core.
  webpack - 4.32.2 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundl
es, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and you
r custom stuff.
  webpack-dev-server - 3.4.1 -- Serves a webpack app. Updates the browser on changes.
  workbox-webpack-plugin - 4.3.1 -- A plugin for your Webpack build process, helping you generate a manifest of loc
al files that workbox-sw should precache.
  register-service-worker - 1.6.2 -- Script for registering service worker, with hooks

Quasar App Extensions
  @quasar/quasar-app-extension-testing-unit-jest - 1.0.0-beta.23 -- A Quasar App Extension for running Jest tests
  @quasar/quasar-app-extension-testing - 1.0.0-rc.8 -- A Quasar App Extension for managing Test Harnesses
  @quasar/quasar-app-extension-icon-factory - 1.0.0-rc.2 -- A Quasar CLI Extension

**Comment by nothingismagick** [comment]
Well, I am at a bit of a loss here - I am on a pretty similar setup and am not having the issue you are reporting.

Can you also paste the contents of `quasar.extensions.json`?

**Comment by s-light** [comment]
i had similar problems -
the icon files did *not* change content if i changed the minification thing but
most of the time they were rebuild without me touching anything icon related..

they went away after i removed my local node_modules package and reinstalled with `yarn`
eventually i had screwed up my global and local folder and file permissions...

**Comment by nothingismagick** [comment]
That's weirdly interesting. That's probably the reason, but I'm actually
rather surprised that the app-extension and Mac is implicated here.

**Comment by s-light** [comment]
for me this was on linux 64bit (Kubuntu 19.04)
i have just started with quasar and did a big bunch of tests and things.. 
so its also easy possible that i did something other that triggered the change in behavior..

**Comment by Makeyko** [comment]
After the latest update it rebuilds only `src/statics/icons/safari-pinned-tab.svg`

quasar.extensions.json:
```
@quasar/icon-factory": {
    "minify_dev": "pngquant",
    "minify_build": "optipng",
    "cordova": {
      "background_color": "#313a5a",
      "splashscreen_type": "generate"
    },
    "build_always": false,
    "__internal": {
      "dev": {
        "spa": {
          "iconHash": "2f15845c6a333dea4000f85ebdd016f3"
        }
      },
      "build": {
        "spa": {
          "iconHash": ""
        }
      }
    }
  }
```

**Comment by nothingismagick** [comment]
Are you using npm for the local dependencies?

>

**Comment by Makeyko** [comment]
yarn

**Comment by nothingismagick** [comment]
Trying to figure this out, and I don’t really understand what’s going on,
so please try the following:

quasar ext remove @quasar/icon-factory
rm yarn.lock
rm -rf node_modules
yarn
quasar ext add @quasar/icon-factory
quasar dev #let build once
quasar dev

**Comment by Makeyko** [comment]
It was interesting and maybe new bug appeared :) 

First time after `quasar dev`: 
was created `src/statics/icons/safari-pinned-tab.svg` and surprisingly `app-splashscreen.png` with warning sign, but during install i set creation of splash with color and icon.

Before second run, i discarded all files changes and no new files was created.

**Comment by nothingismagick** [comment]
Perhaps I need to update the documentation. The app-splash screen.png is
dropped in there by default, no matter what you choose, in case you change
your mind later.

The svg is created because we don’t provide it by default.

The extension will only run if you change the source images.

**Comment by Makeyko** [comment]
Ok, thank you ;) Main issue (icons rebuild every run) — solved ;)
