### ISSUE TITLE
Output path: not clear how to configure

### ISSUE THREAD

**Issue by jigarzon** [quasarframework/app-extension-icon-factory#65]
Right out of the box, I run `quasar dev -m ssr` and the icons are generated on the `/statics/icons` directory.
This directory doesn't integrate with default quasar directory structure: https://quasar.dev/quasar-cli/cli-documentation/directory-structure#Introduction, that says that they should be in `/src/statics/icons`

I cannot find any docs for configuring the output dir. This is my current config (tried to set `output` variable without success):
```
"@quasar/icon-factory": {
    "minify_dev": "optipng",
    "minify_build": "zopfli",
    "cordova": {
      "background_color": "#00b588",
      "splashscreen_type": "pure"
    },
    "output": "src",
    "build_always": false,
    "__internal": {
      "dev": {
        "spa": {
          "iconHash": "83f2df02feb532963fa26595daebacd6"
        }
      },
      "build": {}
    }
  }
```

**Comment by nothingismagick** [comment]
it doesn't put the files in `/src/statics/icons` ?

**Comment by jigarzon** [comment]
Nope, they are on the root/statics/icons

**Comment by nothingismagick** [comment]
Thanks for reporting - I'll fix this right now.

**Comment by nothingismagick** [comment]
Available now in v1.0.0-rc.3

**Comment by nothingismagick** [comment]
@jigarzon - can you confirm its working as expected now?

**Comment by jigarzon** [comment]
Yes its working, thanks a lot for such a quick fix, you rock guys, and also quasar v1 does!
