### ISSUE TITLE
quasar build is replacing the icons in src/static

### ISSUE THREAD

**Issue by fergusmeiklejohn** [quasarframework/app-extension-icon-factory#67]
When I run `quasar build` it's creating icons in dist/spa/statics but also replacing the icons in src/static, this causes `quasar dev` to rebuild the icons again.

quasar.extensions.json "dev" and "build" have the same "iconHash"

**Comment by nothingismagick** [comment]
Do they have the same minify target?

**Comment by fergusmeiklejohn** [comment]
Different Minify target: dev is "pngquant" and build is "optipng"
