### ISSUE TITLE
Error: App Extension "@quasar/icon-factory" has missing index script...

### ISSUE THREAD

**Issue by tanthammar** [quasarframework/app-extension-icon-factory#71]
- Quasar v1.0.0-rc.4
- @quasar/quasar-app-extension-icon-factory 1.0.0-rc.5

Trying to follow installation instructions but when I run `Quasar dev -m pwa` or `Quasar dev -m electron` I get this error:
```js
App Extension "@quasar/icon-factory" has missing index script...
``` 
`quasar.extionsions.json`
```json
{
  "@quasar/icon-factory": {
    "minify_dev": "pngquant",
    "minify_build": "zopfli",
    "cordova": {
      "background_color": "#000074",
      "splashscreen_type": "generate"
    },
    "build_always": false
  }
}
````

**Comment by nothingismagick** [comment]
please show the full results of

quasar info

>

**Comment by nothingismagick** [comment]
and it should be
... quasar.extensions.json

I am assuming you made a typo

>

**Comment by nothingismagick** [comment]
If this is still an issue, please upgrade and reopen.
